### PR TITLE
1.0.8

### PR DESCRIPTION
**Pull request by kjellr**
* Add block editor theme tags
* Correct text color rules for nested blocks
* Tidy up translation functions and comments

### CODE REVIEW

**Comment by kjellr** [comment]
(Waiting on [a decision here](https://href.li/?https://github.com/Automattic/themes/pull/2448) regarding the minimum theme version).

**Comment by kjellr** [comment]
This is good to go. I will upload to WP.org as soon as the automated ThemeCheck there allows use of the `block-patterns` tag (that tag is currently blocked, but an update is pending). 

I'll update this ticket once that's complete.

**Comment by jffng** [comment]
We should revisit the script that strips the dotcom specific aspects of the theme and generates a .org ready version, so that we don't need to maintain this repo anymore. I started this as a temporary repo to juggle between getting the theme on dotcom and dotorg simultaneously, but I would hope that we can make this repo unnecessary through some scripting / automation.

**Comment by kjellr** [comment]
This update was submitted to WP.org, minus the `block-patterns` tag. https://themes.trac.wordpress.org/ticket/89864

**Pull request merged**
